blank_issues_enabled: false
contact_links:
  - name: Telegram Bot Kambo Klarity Discussions
    url: https://github.com/yourusername/kambo-klarity-bot/discussions
    about: Please ask and answer questions here.